### ISSUE TITLE
Profile template 

### ISSUE THREAD

**Issue by cmharlow** [cmh2166/hyrax_data_migration#1]
To aid gathering or generation of MAPs where needed

**Comment by vantuyls** [comment]
suggested profile template? https://github.com/no-reply/sufia-profile/blob/master/profile.md

**Comment by cmharlow** [comment]
that is basically the PCDM profile somewhat taken from the HyBox Models attempted revamp which was influenced by some of the early CUL + LD4L model docs. Will take a pass at abstracting all of these into a template that hits the right point of complexity + detail with comprehensibility.
